EMSProject/Controllers/DashboardController.cs
using EMSProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EMSProject.Controllers
{
    public class DashboardController : Controller
    {
        private EMSEntitiesdb db = new EMSEntitiesdb();

        // GET: equip
        public ActionResult Index()
        {
            var totalequipments = db.equipments.ToList().Count();
            var equiplist = db.equipments.ToList();
            var totalCategories = db.categories.Count();
            // Calculate the sum of the price field
            var totalPriceSum = db.equipments.Sum(p => p.price);

            // Store the total price sum in ViewBag
            ViewBag.TotalPriceSum = totalPriceSum;
            ViewBag.TotalEquipments = totalequipments;
            ViewBag.TotalCategories = totalCategories;

            return View(equiplist);
        }

    }
}

EMSProject/Controllers/EquipmentController.cs
using EMSProject.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EMSProject.Controllers
{
    public class EquipmentController : Controller
    {
        private EMSEntitiesdb db = new EMSEntitiesdb();

        // GET: equip
        public ActionResult Index()
        {
            var equipments = db.equipments.Include(e => e.category);
            
            return View(equipments.ToList());
        }

        // GET: equip/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            equipment equipment = db.equipments.Find(id);
            if (equipment == null)
            {
                return HttpNotFound();
            }
            return View(equipment);
        }

        // GET: equip/Create
        public ActionResult Create()
        {
            ViewBag.equiptype = new SelectList(db.categories, "id", "name");
            return View();
        }

        // POST: equip/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,price,equiptype,purchdate")] equipment equipment)
        {
            if (ModelState.IsValid)
            {
                db.equipments.Add(equipment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.equiptype = new SelectList(db.categories, "id", "name", equipment.equiptype);
            return View(equipment);
        }

        // GET: equip/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            equipment equipment = db.equipments.Find(id);
            if (equipment == null)
            {
                return HttpNotFound();
            }
            ViewBag.equiptype = new SelectList(db.categories, "id", "name", equipment.equiptype);
            return View(equipment);
        }

        // POST: equip/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,price,equiptype,purchdate")] equipment equipment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(equipment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.equiptype = new SelectList(db.categories, "id", "name", equipment.equiptype);
            return View(equipment);
        }

        // GET: equip/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            equipment equipment = db.equipments.Find(id);
            if (equipment == null)
            {
                return HttpNotFound();
            }
            return View(equipment);
        }

        // POST: equip/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            equipment equipment = db.equipments.Find(id);
            db.equipments.Remove(equipment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

EMSProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @* DataTables CDNs *@
    <!-- Bootstrap CSS -->
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">







    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>




    <script src="~/Scripts/JSCustom.js"></script>




</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("EMS", "Index", "Equipment", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">

                    <li>@Html.ActionLink("Home", "Index", "Dashboard", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Equipments", "Index", "Equipment", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Category", "Index", "Category", new { area = "" }, new { @class = "nav-link" })</li>
                 
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <br />

        @RenderBody()
        <hr />
        <footer style="text-align:center;">
            <b>&copy; @DateTime.Now.Year - EMS</b>
        </footer>
    </div>


    
    
    @RenderSection("scripts", required: false)
</body>
</html>